export const SpecialKeys = {
  Backspace: "backspace",
  Tab: "tab",
  Clear: "clear",
  Enter: "enter",
  Esc: "esc",
  Space: "space",
  Up: "up",
  Down: "down",
  Left: "left",
  Right: "right",
  Pageup: "pageup",
  Pagedown: "pagedown",
  Del: "del",
  F1: "f1",
  F2: "f2",
  F3: "f3",
  F4: "f4",
  F5: "f5",
  F6: "f6",
  F7: "f7",
  F8: "f8",
  F9: "f9",
  F10: "f10",
  F11: "f11",
  F12: "f12",
} as const

export type SpecialType = (typeof SpecialKeys)[keyof typeof SpecialKeys]
